### ISSUE TITLE
Lang directory not working after upgrade

### ISSUE THREAD

**Issue by JmRy** [laravel-shift/laravel-9.x#1]
Hello Team,

Laravel 9 moved the `resources/lang` folder to the top level of the project. 

It's OK You move the folder. But you don't delete the old folder `resources/lang` !

Result, the project always looks the files translation in the old folder.

At a minimum, indicate in your report that you did not delete the old file. This will avoid looking for why the texts are not translated ...

Solution found > [https://stackoverflow.com/questions/71084830/laravel-9-app-upgraded-from-8-lang-directory-not-working-as-expected](https://stackoverflow.com/questions/71084830/laravel-9-app-upgraded-from-8-lang-directory-not-working-as-expected)

Thank's 😉

**Comment by laravel-shift** [comment]
Please contact support with you Shift number to report any issues or feedback.
